
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oywqdbajezhdabkuueqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95d3FkYmFqZXpoZGFia3V1ZXF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MzcxMTQsImV4cCI6MjA1OTIxMzExNH0.7v2BCn6KadTOWV2exXGR14DTQEFMsPGT594YxJ6S16Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
